# Start mongodb: docker-compose up
# Start interactive client: docker exec -it theblogapp-mongodb-1 mongoshga
version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6:
